# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.vm.box = "ubuntu/trusty64"
  config.hostmanager.manage_host = true

  config.vm.define "control01", primary: true do |h|
    h.vm.network "private_network", ip: "192.168.135.10"
    h.vm.provision "shell", path: "scripts/add_ansible_user.sh" 
    h.vm.provision "shell", path: "scripts/generate_ansible_ssh_keys.sh" 
    h.vm.provision "shell", path: "scripts/install_ansible.sh" 
    h.vm.provision "shell", path: "scripts/populate_inventory.sh" 
    h.vm.provision "shell", path: "scripts/install_git.sh"
    h.vm.provision "shell", path: "scripts/clone_git_repo.sh" 
    h.vm.provision :shell, inline: 'sudo -u ansible mkdir /home/ansible/work'
    h.vm.provision :shell, inline: 'sudo -u ansible echo "export DOCKER_HOST=docker01" > /home/ansible/.bash_profile'
    #h.vm.provision "shell", path: "scripts/install_docker_client.sh"
    #h.vm.provision "shell", path: "scripts/install_docker.sh"
    h.vm.provision "shell", path: "scripts/install_control01_software.sh"
    h.vm.synced_folder "../ansible", "/ansible", disabled: false,  owner: "1002", group: "1002"
    h.vm.hostname = "control01"
    h.vm.provider :virtualbox do |vb|
        vb.name = "control01"
    end
  end

  config.vm.define "lb01" do |h|
    h.vm.network "private_network", ip: "192.168.135.101"
    h.vm.provision :shell, path: "scripts/add_ansible_user.sh"
    h.vm.provision :shell, inline: 'cat /vagrant/control.pub > /home/ansible/.ssh/authorized_keys'
    h.vm.hostname = "lb01"
    h.vm.provider :virtualbox do |vb|
        vb.name = "lb01"
    end
  end

  config.vm.define "app01" do |h|
    h.vm.network "private_network", ip: "192.168.135.111"
    h.vm.provision :shell, path: "scripts/add_ansible_user.sh"
    h.vm.provision :shell, inline: 'cat /vagrant/control.pub > /home/ansible/.ssh/authorized_keys'
    h.vm.hostname = "app01"
    h.vm.provider :virtualbox do |vb|
        vb.name = "app01"
    end
  end

  config.vm.define "app02" do |h|
    h.vm.network "private_network", ip: "192.168.135.112"
    h.vm.provision :shell, path: "scripts/add_ansible_user.sh"
    h.vm.provision :shell, inline: 'cat /vagrant/control.pub > /home/ansible/.ssh/authorized_keys'
    h.vm.hostname = "app02"
    h.vm.provider :virtualbox do |vb|
        vb.name = "app02"
    end
  end

  config.vm.define "db01" do |h|
    h.vm.network "private_network", ip: "192.168.135.121"
    h.vm.provision :shell, path: "scripts/add_ansible_user.sh"
    h.vm.provision :shell, inline: 'cat /vagrant/control.pub >> /home/ansible/.ssh/authorized_keys'
    h.vm.hostname = "db01"
    h.vm.provider :virtualbox do |vb|
        vb.name = "db01"
    end
  end

  config.vm.define "docker01" do |h|
    h.vm.network "private_network", ip: "192.168.135.131"
    h.vm.provision :shell, path: "scripts/add_ansible_user.sh"
    h.vm.provision "shell", path: "scripts/install_docker.sh"
    h.vm.provision :shell, inline: 'cat /vagrant/control.pub >> /home/ansible/.ssh/authorized_keys'
    h.vm.hostname = "docker01"
    h.vm.provider :virtualbox do |vb|
        vb.name = "docker01"
    end
  end

end
